# Generated by Django 4.2.6 on 2023-10-13 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=13)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='РФ', max_length=40)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DetailName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('article', models.CharField(blank=True, max_length=20, null=True)),
                ('details_quantity', models.SmallIntegerField(default=1)),
                ('deleted', models.BooleanField(default=False)),
                ('color_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.colorscheme')),
            ],
        ),
        migrations.CreateModel(
            name='MasterBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(max_length=140)),
                ('doze', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_material_doze', models.DecimalField(decimal_places=2, max_digits=4)),
                ('main_master_doze', models.DecimalField(decimal_places=2, max_digits=4)),
                ('add_master_doze', models.DecimalField(decimal_places=2, max_digits=4)),
                ('add_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional', to='production.masterbatch')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.goods')),
                ('main_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='production.masterbatch')),
                ('main_material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.materialtype')),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('stock_address', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=40, null=True)),
                ('mail', models.CharField(blank=True, max_length=140, null=True)),
                ('contact', models.CharField(blank=True, max_length=250, null=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.country')),
            ],
        ),
        migrations.AddField(
            model_name='masterbatch',
            name='material_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.materialtype'),
        ),
        migrations.AddField(
            model_name='masterbatch',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.producer'),
        ),
        migrations.CreateModel(
            name='MainMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(max_length=140)),
                ('material_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.materialtype')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.producer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailInGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.SmallIntegerField(default=1)),
                ('deleted', models.BooleanField(default=False)),
                ('detail_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.detailname')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.goods')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_id', models.CharField(max_length=10)),
                ('pantone', models.CharField(default='', max_length=20)),
                ('color_name', models.CharField(max_length=60)),
                ('color_code', models.CharField(max_length=7)),
                ('deleted', models.BooleanField(default=False)),
                ('color_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.colorscheme')),
            ],
        ),
        migrations.CreateModel(
            name='AddMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('material_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.materialtype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
