# Generated by Django 4.2.6 on 2023-10-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_delete_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_material_doze', models.DecimalField(decimal_places=2, max_digits=4)),
                ('main_master_doze', models.DecimalField(decimal_places=2, max_digits=4)),
                ('add_master_doze', models.DecimalField(decimal_places=2, max_digits=4)),
                ('add_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional', to='production.masterbatch')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.color')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.goods')),
                ('main_master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='production.masterbatch')),
                ('main_material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.materialtype')),
            ],
        ),
    ]
