# Generated by Django 4.2.6 on 2023-10-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_materialtype_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
