# Generated by Django 4.2.6 on 2023-10-15 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_detailingoods_detail_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=2)),
                ('producer_code', models.CharField(max_length=20)),
                ('account_code', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=140)),
                ('imm_model', models.CharField(max_length=140)),
                ('in_work', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.producer')),
            ],
        ),
    ]
