# Generated by Django 4.2.6 on 2023-10-17 18:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0007_imm'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1000)),
                ('quantity_left', models.IntegerField(default=1000)),
                ('date_create', models.DateTimeField(default=datetime.datetime(2023, 10, 17, 21, 25, 5, 484820))),
                ('if_order', models.BooleanField(default=True)),
                ('closed', models.BooleanField(default=False)),
                ('date_close', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('color', models.ForeignKey(limit_choices_to={'color__color_scheme': models.F('detail__goods__color_scheme')}, on_delete=django.db.models.deletion.CASCADE, to='production.color')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.detailingoods')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='imm',
            name='in_work',
        ),
        migrations.CreateModel(
            name='ProductionRequestStartStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(default=datetime.datetime(2023, 10, 17, 21, 25, 5, 484820))),
                ('date_stop', models.DateTimeField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=140, null=True)),
                ('imm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.imm')),
                ('production_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionrequest')),
                ('user_start', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_start', to=settings.AUTH_USER_MODEL)),
                ('user_stop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_stop', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 10, 17, 21, 25, 5, 485671))),
                ('quantity', models.IntegerField(default=1000)),
                ('deleted', models.BooleanField(default=False)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.color')),
                ('detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.detailingoods')),
                ('imm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.imm')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
