# Generated by Django 4.2.6 on 2023-10-19 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0008_productionrequest_remove_imm_in_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionreport',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productionrequest',
            name='date_create',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productionrequest',
            name='quantity_left',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productionrequeststartstop',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='QualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_checked', models.IntegerField(default=0)),
                ('quantity_approved', models.IntegerField(default=0)),
                ('date_check', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('production', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionreport')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
