# Generated by Django 4.2.6 on 2023-10-19 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_alter_productionreport_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionForRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionreport')),
                ('production_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionrequest')),
            ],
        ),
    ]
