# Generated by Django 4.2.6 on 2023-10-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_productionforrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreport',
            name='defect',
            field=models.IntegerField(default=0),
        ),
    ]
