# Generated by Django 4.2.6 on 2023-10-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_productionrequest_technical'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Defects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QualityReportDefects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('defect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.defects')),
                ('quality_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.qualityreport')),
            ],
        ),
    ]
