# Generated by Django 4.2.6 on 2023-10-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_defectevent_defects_qualityreportdefects'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityreport',
            name='comment',
            field=models.CharField(default='', max_length=255),
        ),
    ]
