# Generated by Django 4.2.6 on 2023-10-26 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_qualityreport_defect_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityForRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_checked', models.IntegerField(default=0)),
                ('quantity_approved', models.IntegerField(default=0)),
                ('production_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionrequest')),
                ('quality_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.qualityreport')),
            ],
        ),
    ]
