# Generated by Django 4.2.6 on 2023-10-26 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_qualityforrequests'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QualityForRequests',
            new_name='QualityForRequest',
        ),
    ]
