# Generated by Django 4.2.6 on 2023-11-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_qualityreportdefects_date_create_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addmaterial',
            options={'ordering': ['material_type__name']},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['color_scheme', 'color_id']},
        ),
        migrations.AlterModelOptions(
            name='colorscheme',
            options={'ordering': ['scheme_name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='defectevent',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='defects',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='detailingoods',
            options={'ordering': ['goods__article', 'position']},
        ),
        migrations.AlterModelOptions(
            name='detailname',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['article']},
        ),
        migrations.AlterModelOptions(
            name='imm',
            options={'ordering': ['plant_code']},
        ),
        migrations.AlterModelOptions(
            name='mainmaterial',
            options={'ordering': ['brand']},
        ),
        migrations.AlterModelOptions(
            name='masterbatch',
            options={'ordering': ['brand']},
        ),
        migrations.AlterModelOptions(
            name='materialtype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['goods__article']},
        ),
        migrations.AddField(
            model_name='productionrequest',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
