# Generated by Django 4.2.6 on 2023-11-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_productionforrequest_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualityforrequest',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
