# Generated by Django 4.2.6 on 2023-12-19 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_qualityforrequest_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreport',
            name='shift_checked',
            field=models.BooleanField(default=False),
        ),
    ]
