# Generated by Django 4.2.6 on 2023-12-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_productionreport_shift_checked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionreport',
            old_name='shift_checked',
            new_name='shift_rejected',
        ),
    ]
