# Generated by Django 4.2.6 on 2024-01-06 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_rename_shift_checked_productionreport_shift_rejected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['color_scheme', 'code']},
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color_id',
            new_name='code',
        ),
    ]
