# Generated by Django 4.2.6 on 2024-01-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_alter_color_options_rename_color_id_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='add_master_doze',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='add_material_doze',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='main_master_doze',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
