# Generated by Django 4.2.6 on 2024-01-07 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0027_alter_recipe_add_master_doze_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='add_material_doze',
        ),
        migrations.AddField(
            model_name='recipe',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='date_closed',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='date_create',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='RecipeDetail',
            fields=[
                ('recipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='production.recipe')),
                ('add_material_doze', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('detail', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.detailingoods')),
                ('main_material', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.mainmaterial')),
                ('production', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productionreport')),
            ],
            bases=('production.recipe',),
        ),
    ]
