# Generated by Django 4.2.6 on 2024-01-07 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0029_alter_recipe_date_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('deleted', models.BooleanField(default=False)),
                ('color_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.colorscheme')),
            ],
        ),
        migrations.AddField(
            model_name='detailingoods',
            name='technical_color_scheme',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.technicalcolorscheme'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='technical_color_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.technicalcolorscheme'),
        ),
    ]
