# Generated by Django 4.2.6 on 2024-01-07 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0030_technicalcolorscheme_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TechnicalColorScheme',
            new_name='RecipeColorScheme',
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['recipe_color_scheme', 'color']},
        ),
        migrations.AlterModelOptions(
            name='recipecolorscheme',
            options={'ordering': ['color_scheme']},
        ),
        migrations.AlterModelOptions(
            name='recipedetail',
            options={'ordering': ['recipe_color_scheme', 'color']},
        ),
        migrations.RenameField(
            model_name='detailingoods',
            old_name='technical_color_scheme',
            new_name='recipe_color_scheme',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='technical_color_scheme',
            new_name='recipe_color_scheme',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='add_master',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='add_master_doze',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='goods',
        ),
        migrations.AddField(
            model_name='recipedetail',
            name='add_master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional', to='production.masterbatch'),
        ),
        migrations.AddField(
            model_name='recipedetail',
            name='add_master_doze',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
