# Generated by Django 4.2.6 on 2024-01-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0031_rename_technicalcolorscheme_recipecolorscheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='standard',
            field=models.BooleanField(default=True),
        ),
    ]
