# Generated by Django 4.2.6 on 2024-01-08 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0032_color_standard'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailBaseWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightG', models.DecimalField(decimal_places=1, default=0, max_digits=6)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.detailingoods')),
            ],
            options={
                'ordering': ['detail', '-date_create'],
            },
        ),
        migrations.CreateModel(
            name='DetailActualWeight',
            fields=[
                ('detailbaseweight_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='production.detailbaseweight')),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionreport')),
            ],
            bases=('production.detailbaseweight',),
        ),
    ]
