# Generated by Django 4.2.6 on 2024-01-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0033_detailbaseweight_detailactualweight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailbaseweight',
            options={'ordering': ['detail_in_goods', '-date_create']},
        ),
        migrations.RenameField(
            model_name='detailbaseweight',
            old_name='detail',
            new_name='detail_in_goods',
        ),
    ]
