# Generated by Django 4.2.6 on 2024-01-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0036_alter_detailbaseweight_weight_g'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailbaseweight',
            name='weight_g',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=9),
        ),
    ]
