# Generated by Django 4.2.6 on 2024-01-09 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0038_equipment_moldbase_accountinfoequipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecolorscheme',
            options={'ordering': ['color_scheme', 'name']},
        ),
    ]
