# Generated by Django 4.2.6 on 2024-01-11 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0039_alter_recipecolorscheme_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailBaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_g', models.DecimalField(decimal_places=3, default=0, max_digits=9)),
                ('cycle_time_seconds', models.IntegerField(default=0)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('detail_in_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.detailingoods')),
            ],
            options={
                'ordering': ['detail_in_goods', '-date_create'],
            },
        ),
        migrations.CreateModel(
            name='MoldInsert',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='production.equipment')),
                ('mount_time_min', models.IntegerField(default=0)),
                ('release_time_min', models.IntegerField(default=0)),
                ('if_modular', models.BooleanField(default=False)),
                ('plant_no', models.CharField(max_length=80)),
                ('cavities_quantity', models.IntegerField()),
                ('air_valves_quantity_moving_plate', models.IntegerField(default=0)),
                ('air_valves_quantity_fixed_plate', models.IntegerField(default=0)),
                ('if_hydraulic', models.BooleanField(default=False)),
                ('hydraulic_quantity_moving_plate', models.IntegerField(default=0)),
                ('hydraulic_quantity_fixed_plate', models.IntegerField(default=0)),
                ('single_insert', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['account_code', 'name'],
                'abstract': False,
            },
            bases=('production.equipment',),
        ),
        migrations.CreateModel(
            name='MoldModifier',
            fields=[
                ('equipment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='production.equipment')),
                ('mount_time_min', models.IntegerField(default=0)),
                ('release_time_min', models.IntegerField(default=0)),
                ('if_modular', models.BooleanField(default=False)),
                ('plant_no', models.CharField(max_length=80)),
                ('height_mm', models.IntegerField()),
                ('weight_kg', models.IntegerField()),
                ('if_air', models.BooleanField(default=False)),
                ('air_valves_quantity_moving_plate', models.IntegerField(default=0)),
                ('air_valves_quantity_fixed_plate', models.IntegerField(default=0)),
                ('single_modifier', models.BooleanField(default=True)),
                ('changeable_insert', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['account_code', 'name'],
                'abstract': False,
            },
            bases=('production.equipment',),
        ),
        migrations.RemoveField(
            model_name='detailbaseweight',
            name='detail_in_goods',
        ),
        migrations.RenameField(
            model_name='moldbase',
            old_name='single_modifier',
            new_name='changeable_modifier',
        ),
        migrations.RenameField(
            model_name='moldbase',
            old_name='hot_runner_no',
            new_name='hot_runner_quantity',
        ),
        migrations.RenameField(
            model_name='moldbase',
            old_name='height_mm',
            new_name='length_mm',
        ),
        migrations.RemoveField(
            model_name='moldbase',
            name='mold_base',
        ),
        migrations.RemoveField(
            model_name='moldbase',
            name='plant_no',
        ),
        migrations.AddField(
            model_name='equipment',
            name='name',
            field=models.CharField(default='', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='producer_model',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.CreateModel(
            name='DetailActualData',
            fields=[
                ('detailbasedata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='production.detailbasedata')),
                ('cavities_quantity_working', models.IntegerField()),
                ('production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionreport')),
            ],
            bases=('production.detailbasedata',),
        ),
        migrations.DeleteModel(
            name='DetailActualWeight',
        ),
        migrations.DeleteModel(
            name='DetailBaseWeight',
        ),
        migrations.AddField(
            model_name='detailbasedata',
            name='mold_insert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.moldinsert'),
        ),
    ]
