# Generated by Django 4.2.6 on 2024-01-12 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0041_clampingunit_ejectortype_screwtype_injectionunit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=140, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='injectionunit',
            name='heat_insulation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='injectionunit',
            name='heating_zones_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injectionunit',
            name='injection_pressure_bar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injectionunit',
            name='injection_speed_cm3_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injectionunit',
            name='l_d_ratio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injectionunit',
            name='material_hopper',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='injectionunit',
            name='material_hopper_volume_l',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injectionunit',
            name='max_injection_volume_cm3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injectionunit',
            name='max_injection_weight_g',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injectionunit',
            name='max_nozzle_stroke_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injectionunit',
            name='max_screw_stroke_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injectionunit',
            name='nozzle_contact_force_kN',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injectionunit',
            name='nozzle_immersion_depth_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injectionunit',
            name='plasticization_speed_g_sec',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ImmGeneralData',
            fields=[
                ('imm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='production.imm')),
                ('oil_tank_volume_l', models.IntegerField(blank=True, null=True)),
                ('pump_electric_capacity_kW', models.IntegerField(blank=True, null=True)),
                ('heating_electric_capacity_kW', models.IntegerField(blank=True, null=True)),
                ('euromap_dry_cycle_time_sec', models.IntegerField(blank=True, null=True)),
                ('euromap_dry_cycle_stroke_mm', models.IntegerField(blank=True, null=True)),
                ('machine_weight_kg', models.IntegerField(blank=True, null=True)),
                ('machine_length_mm', models.IntegerField(blank=True, null=True)),
                ('machine_width_mm', models.IntegerField(blank=True, null=True)),
                ('machine_height_mm', models.IntegerField(blank=True, null=True)),
                ('imm_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.immtype')),
            ],
        ),
        migrations.CreateModel(
            name='ImmAdditionalOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotameter_quantity', models.IntegerField(blank=True, null=True)),
                ('euromap_interface', models.BooleanField(default=False)),
                ('in_out_programming_interface', models.BooleanField(default=False)),
                ('in_out_production_interface_quantity', models.IntegerField(blank=True, null=True)),
                ('hydraulic_cylinder_moving_plate', models.BooleanField(default=False)),
                ('hydraulic_cylinder_moving_plate_quantity', models.IntegerField(blank=True, null=True)),
                ('hydraulic_cylinder_fixed_plate', models.BooleanField(default=False)),
                ('hydraulic_cylinder_fixed_plate_quantity', models.IntegerField(blank=True, null=True)),
                ('air_valve_moving_plate', models.BooleanField(default=False)),
                ('air_valve_moving_plate_quantity', models.IntegerField(blank=True, null=True)),
                ('air_valve_fixed_plate', models.BooleanField(default=False)),
                ('air_valve_fixed_plate_quantity', models.IntegerField(blank=True, null=True)),
                ('hot_runnel_control', models.BooleanField(default=False)),
                ('hot_runnel_control_zones', models.IntegerField(blank=True, null=True)),
                ('imm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='production.imm')),
            ],
        ),
    ]
