# Generated by Django 4.2.6 on 2024-01-13 17:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0043_ejectortype_deleted_immtype_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailProducingParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.color')),
                ('detail_base_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.detailbasedata')),
                ('imm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.imm')),
            ],
            options={
                'ordering': ['imm', 'detail_base_data__detail_in_goods'],
            },
        ),
        migrations.CreateModel(
            name='EjectorConnectorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=140, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialInjection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imm_page', models.IntegerField(blank=True, null=True)),
                ('pressure_bar', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True)),
                ('injection_time_sec', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True)),
                ('position_before_switch_mm', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True)),
                ('detail_producing_parameters', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.detailproducingparameters')),
            ],
        ),
        migrations.CreateModel(
            name='MoldTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imm_page', models.IntegerField(blank=True, null=True)),
                ('core_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('cavity_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('detail_producing_parameters', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.detailproducingparameters')),
            ],
        ),
        migrations.CreateModel(
            name='MoldProtectionParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imm_page', models.IntegerField(blank=True, null=True)),
                ('mold_protection_start_mm', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True)),
                ('mold_protection_end_mm', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True)),
                ('mold_protection_force_kN', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True)),
                ('mold_protection_time_sec', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True)),
                ('detail_producing_parameters', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.detailproducingparameters')),
            ],
        ),
        migrations.CreateModel(
            name='MoldHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imm_page', models.IntegerField(blank=True, null=True)),
                ('position_mm', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('speed_percent', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('holding_time_sec', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('start_pressure_bar', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('end_pressure_bar', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('detail_producing_parameters', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.detailproducingparameters')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialLoading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imm_page', models.IntegerField(blank=True, null=True)),
                ('position_mm', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('pressure_bar', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True)),
                ('speed_mm_sec', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True)),
                ('back_pressure_bar', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True)),
                ('decompression_mm', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('detail_producing_parameters', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.detailproducingparameters')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialInjectionPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_no', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('position_mm', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('injection_speed_mm_sec', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True)),
                ('material_injection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.materialinjection')),
            ],
            options={
                'ordering': ['position_no'],
            },
        ),
        migrations.CreateModel(
            name='ImmZonesTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_no', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(6)])),
                ('zone_temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mold_temperature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.moldtemperature')),
            ],
            options={
                'ordering': ['zone_no'],
            },
        ),
        migrations.CreateModel(
            name='HydraulicCoresParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imm_page', models.IntegerField(blank=True, null=True)),
                ('detail_producing_parameters', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.detailproducingparameters')),
            ],
        ),
        migrations.CreateModel(
            name='HydraulicCoresMoving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward', models.BooleanField(default=True)),
                ('core_no', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('pressure_bar', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True)),
                ('position_mm', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('speed_mm_sec', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True)),
                ('time_sec', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True)),
                ('hydraulic_core_parameters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.hydrauliccoresparameters')),
            ],
            options={
                'ordering': ['core_no', 'forward'],
            },
        ),
        migrations.CreateModel(
            name='HotRunnerZonesTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_no', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)])),
                ('zone_temperature', models.DecimalField(decimal_places=2, max_digits=6)),
                ('mold_temperature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.moldtemperature')),
            ],
            options={
                'ordering': ['zone_no'],
            },
        ),
        migrations.CreateModel(
            name='EjectorParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imm_page', models.IntegerField(blank=True, null=True)),
                ('pressure_bar', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('speed_mm_sec', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('timeout_forward_sec', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('timeout_backward_sec', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('stroke_quantity', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('position_forward_mm', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('position_backward_mm', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('detail_producing_parameters', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.detailproducingparameters')),
            ],
        ),
        migrations.CreateModel(
            name='CoolingParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imm_page', models.IntegerField(blank=True, null=True)),
                ('timeout_loading_sec', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('cooling_time_sec', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('imm_time_sec', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('detail_producing_parameters', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.detailproducingparameters')),
            ],
        ),
        migrations.CreateModel(
            name='ClampingUnitParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imm_page', models.IntegerField(blank=True, null=True)),
                ('clamping_force_kN', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=6, null=True)),
                ('detail_producing_parameters', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.detailproducingparameters')),
            ],
        ),
        migrations.CreateModel(
            name='ClampingUnitMoving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_no', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('position_mm', models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=5, null=True)),
                ('opening', models.BooleanField(default=False)),
                ('clamping_unit_parameters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.clampingunitparameters')),
            ],
            options={
                'ordering': ['opening', 'position_no'],
            },
        ),
        migrations.AddField(
            model_name='moldbase',
            name='ejector_connector_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.ejectorconnectortype'),
        ),
    ]
