# Generated by Django 4.2.6 on 2024-01-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0044_detailproducingparameters_ejectorconnectortype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clampingunit',
            options={'ordering': ['imm']},
        ),
        migrations.AlterModelOptions(
            name='ejector',
            options={'ordering': ['imm']},
        ),
        migrations.AlterModelOptions(
            name='ejectortype',
            options={'ordering': ['type']},
        ),
        migrations.AlterModelOptions(
            name='immadditionaloptions',
            options={'ordering': ['imm']},
        ),
        migrations.AlterModelOptions(
            name='immgeneraldata',
            options={'ordering': ['imm']},
        ),
        migrations.AlterModelOptions(
            name='immtype',
            options={'ordering': ['type']},
        ),
        migrations.AlterModelOptions(
            name='injectionunit',
            options={'ordering': ['imm']},
        ),
        migrations.AlterModelOptions(
            name='screwtype',
            options={'ordering': ['geometry']},
        ),
    ]
