# Generated by Django 4.2.6 on 2024-01-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0045_alter_clampingunit_options_alter_ejector_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moldbase',
            options={'ordering': ['account_code', 'name']},
        ),
        migrations.AddField(
            model_name='moldbase',
            name='if_modular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moldbase',
            name='mount_time_min',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moldbase',
            name='plant_no',
            field=models.CharField(default='F', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moldbase',
            name='release_time_min',
            field=models.IntegerField(default=0),
        ),
    ]
