# Generated by Django 4.2.6 on 2024-01-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0046_alter_moldbase_options_moldbase_if_modular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='РФ', max_length=40, unique=True),
        ),
    ]
