# Generated by Django 4.2.6 on 2024-01-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0047_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorscheme',
            name='scheme_name',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
