# Generated by Django 4.2.6 on 2024-01-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0051_alter_goods_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialtype',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
