# Generated by Django 4.2.6 on 2024-01-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0052_alter_materialtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipecolorscheme',
            name='name',
            field=models.CharField(max_length=140, unique=True),
        ),
    ]
