# Generated by Django 4.2.6 on 2024-01-14 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0053_alter_recipecolorscheme_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moldinsert',
            name='air_valves_quantity_fixed_plate',
        ),
        migrations.RemoveField(
            model_name='moldinsert',
            name='air_valves_quantity_moving_plate',
        ),
    ]
