# Generated by Django 4.2.6 on 2024-01-14 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0055_clampingunit_flange_fixed_mm_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clampingunitparameters',
            options={'ordering': ['detail_producing_parameters']},
        ),
        migrations.AlterModelOptions(
            name='coolingparameters',
            options={'ordering': ['detail_producing_parameters']},
        ),
        migrations.AlterModelOptions(
            name='ejectorparameters',
            options={'ordering': ['detail_producing_parameters']},
        ),
        migrations.AlterModelOptions(
            name='hydrauliccoresparameters',
            options={'ordering': ['detail_producing_parameters']},
        ),
        migrations.AlterModelOptions(
            name='materialinjection',
            options={'ordering': ['detail_producing_parameters']},
        ),
        migrations.AlterModelOptions(
            name='materialloading',
            options={'ordering': ['detail_producing_parameters']},
        ),
        migrations.AlterModelOptions(
            name='moldholding',
            options={'ordering': ['detail_producing_parameters']},
        ),
        migrations.AlterModelOptions(
            name='moldprotectionparameters',
            options={'ordering': ['detail_producing_parameters']},
        ),
        migrations.AlterModelOptions(
            name='moldtemperature',
            options={'ordering': ['detail_producing_parameters']},
        ),
    ]
