# Generated by Django 4.2.6 on 2024-01-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0056_alter_clampingunitparameters_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immadditionaloptions',
            old_name='hot_runnel_control',
            new_name='hot_runner_control',
        ),
        migrations.RenameField(
            model_name='immadditionaloptions',
            old_name='hot_runnel_control_zones',
            new_name='hot_runner_control_zones',
        ),
    ]
