# Generated by Django 4.2.6 on 2024-01-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0057_rename_hot_runnel_control_immadditionaloptions_hot_runner_control_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clampingunit',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ejector',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='immadditionaloptions',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='immgeneraldata',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='injectionunit',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
