# Generated by Django 4.2.6 on 2024-01-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0058_clampingunit_deleted_ejector_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screwtype',
            name='bimetallic',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='screwtype',
            name='resistance',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
