# Generated by Django 4.2.6 on 2024-01-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0059_alter_screwtype_bimetallic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immgeneraldata',
            name='euromap_dry_cycle_time_sec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
