# Generated by Django 4.2.6 on 2024-01-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0060_alter_immgeneraldata_euromap_dry_cycle_time_sec'),
    ]

    operations = [
        migrations.AddField(
            model_name='clampingunit',
            name='max_mold_weight_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clampingunit',
            name='max_mold_weight_per_plate_kg',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
