# Generated by Django 4.2.6 on 2026-03-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0061_clampingunit_max_mold_weight_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='article',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
